# -*- coding: utf-8 -*-
"""Amazon_Sales_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u2q7ZFh5AP06tw8J_VpQRx3_ZeyMeXuO

**Importing Libraries / Dependencies :**
"""

import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

"""**Loading the Data (.csv file) :**"""

df = pd.read_csv('/content/Amazon Sales data.csv')

"""**Data Exploration & Cleaning :**"""

df.shape

df.head()

df.columns

df.info()

# checking for null values
pd.isnull(df).sum()

# checking for duplicate values
df.duplicated().value_counts()

# descriptive statistics
df.describe()

df[['Units Sold','Unit Price','Unit Cost','Total Revenue','Total Cost','Total Profit']].describe()

"""**Exporting Dataframe into csv file (Clean data) :**"""

df.to_csv('Clean_Sales_Data.csv',index=False)